apiVersion: v1
kind: Secret
metadata:
  name: irtdp-secrets
type: Opaque
stringData:
  POSTGRES_DB: "irtdp"
  POSTGRES_USER: "irtdp_prod"
  POSTGRES_PASSWORD: "CHANGE_ME_PRODUCTION_DB_PASSWORD"
  REDIS_PASSWORD: "CHANGE_ME_PRODUCTION_REDIS_PASSWORD"
  JWT_SECRET: "CHANGE_ME_64_BYTE_LONG_SECURE_CRYPTO_KEY"
  MINIO_ROOT_USER: "admin"
  MINIO_ROOT_PASSWORD: "CHANGE_ME_PRODUCTION_MINIO_PASSWORD"
